name: 🌐 Extension request
description: Suggest a new source extension
labels: [Extension request]
body:
  - type: input
    id: name
    attributes:
      label: Source name
      placeholder: ExampleScans
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Source URL
      placeholder: https://examplescans.com
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Source language
      placeholder: English
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      description: Additional details and attachments.
      placeholder: 18+/NSFW = yes

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have checked that the extension does not already exist.
          required: true
        - label: I have written a meaningful title with the source name.
          required: true
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have filled out all of the requested information in this form.
          required: true
